# Generated by Django 6.0.3 on 2026-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_report_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Jalan Rusak', 'Jalan Rusak'), ('Sampah', 'Sampah'), ('Lampu Mati', 'Lampu Mati'), ('Drainase', 'Drainase'), ('Keamanan', 'Keamanan')], max_length=100),
        ),
    ]
