# Generated by Django 6.0.3 on 2026-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Jalan', 'Jalan'), ('Sampah', 'Sampah'), ('Banjir', 'Banjir'), ('Lampu', 'Lampu'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('REPORTED', 'Dilaporkan'), ('VERIFIED', 'Diverifikasi'), ('IN_PROGRESS', 'Diproses'), ('RESOLVED', 'Selesai')], default='REPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
