# Generated by Django 6.0.3 on 2026-04-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Dilaporkan'), ('VERIFIED', 'Diverifikasi'), ('IN_PROGRESS', 'Diproses'), ('RESOLVED', 'Selesai')], default='REPORTED', max_length=20),
        ),
    ]
