# Generated by Django 6.0.3 on 2026-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Jalan', 'Jalan'), ('Sampah', 'Sampah'), ('Banjir', 'Banjir'), ('Lampu', 'Lampu'), ('Lainnya', 'Lainnya')], max_length=100),
        ),
    ]
