# Generated by Django 6.0.3 on 2026-04-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kategori', models.CharField(choices=[('Saran', 'Saran'), ('Keluhan', 'Keluhan'), ('Kendala', 'Kendala')], max_length=20)),
                ('isi', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
